### ISSUE TITLE
User doesn't get their corresponding info 

### ISSUE THREAD

**Issue by quipcode** [machever/ga_admissions_app#36]
---- what happens --- 
After you log in. And click on the github link. The response is a json from github that doesn't reflect me as the user. Instead you get https://api.github.com/users/kaymmx
--- what should happen --- 
I would like to get access to my github 
--- steps to replicate ---- 
1) login as student or instructor
2) once logged in click on the github link 
3) you get redirected to https://api.github.com/users/kaymmx
--- os/browser ---- 
I have a mac and use google chrome....that's all I wrote 
--- screenshot  --- 
![screen shot 2016-05-05 at 9 34 39 am](https://cloud.githubusercontent.com/assets/16657751/15049725/bcd886cc-12a4-11e6-9b00-108a986f2882.png)

**Comment by erkgmz** [comment]
Thanks for finding this @quipcode!
